CELL_PADDING = 10;
CELL_SIZE = 64;
CELL_SPACING = 5;
CELL_STEP = CELL_SIZE + CELL_SPACING;
HERO_SIZE = CELL_SIZE / 2;

HERO_ALLIANCES = {
    "dk": ["human", "dragon", "knight"],
    "tinker": ["goblin", "mech"],
    "clock": ["goblin", "mech"],
    "am": ["elf", "demon_hunter"],
    "axe": ["warrior", "brawny"],
    "batrider": ["knight", "troll"],
    "bloodseeker": ["assassin", "human", "deadeye"],
    "bh": ["assassin", "goblin"],
    "drow": ["undead", "hunter"],
    "enchantress": ["nature", "savage"],
    "ogre": ["mage", "bloodbound"],
    "razor": ["mage", "primordial"],
    "rhasta": ["troll", "shaman"],
    "tiny": ["primordial", "warrior"],
    "tusk": ["warrior", "savage"],
    "venom": ["warlock", "savage"],
    "the_warlock": ["warlock", "bloodbound"],
    "beast": ["brawny", "hunter"],
    "ck": ["knight", "demon"],
    "lina": ["human", "mage"],
    "luna": ["elf", "knight"],
    "morph": ["primordial", "assassin"],
    "furion": ["nature", "elf"],
    "puck": ["dragon", "elf", "mage"],
    "pudge": ["undead", "warrior"],
    "qop": ["assassin", "demon"],
    "slardar": ["scaled", "warrior"],
    "timber": ["goblin", "mech"],
    "wr": ["elf", "hunter"],
    "wd": ["troll", "warlock"],
    "abaddon": ["undead", "knight"],
    "rylai": ["mage", "human"],
    "jugg": ["warrior", "brawny"],
    "lycan": ["human", "savage", "hunter"],
    "omni": ["human", "knight"],
    "mortred": ["elf", "assassin"],
    "sf": ["demon", "warlock"],
    "slark": ["scaled", "assassin"],
    "sniper": ["goblin", "hunter", "deadeye"],
    "tb": ["demon", "demon_hunter"],
    "treant": ["nature", "elf"],
    "viper": ["assassin", "dragon"],
    "alch": ["goblin", "warlock"],
    "arc": ["primordial", "shaman"],
    "ruptor": ["warlock", "brawny"],
    "doom": ["warrior", "demon"],
    "kotol": ["human", "mage"],
    "kunkka": ["human", "warrior"],
    "syllabear": ["nature", "savage"],
    "potm": ["elf", "hunter"],
    "necrolyte": ["warlock", "undead"],
    "crixalis": ["assassin", "savage"],
    "ta": ["elf", "assassin"],
    "tide": ["scaled", "warrior"],
    "eni": ["primordial", "shaman"],
    "gyro": ["deadeye", "mech"],
    "lich": ["mage", "undead"],
    "gorgon": ["scaled", "hunter"],
    "techies": ["goblin", "mech"],
    "troll_warlord": ["troll", "warrior"],
};

ALLIANCE_REQUIREMENTS = {
    "human": [2, 4, 6],
    "undead": [2, 4, 6],
    "elf": [3, 6, 9],
    "savage": [2, 4, 6],
    "scaled": [2, 4],
    "goblin": [2, 4, 6],
    "demon": [1],
    "primordial": [2, 4],
    "dragon": [2],
    "bloodbound": [2],
    "brawny": [2, 4],
    "deadeye": [2],
    "troll": [2, 4],
    "assassin": [3, 6, 9],
    "mage": [3, 6],
    "warrior": [3, 6, 9],
    "knight": [2, 4, 6],
    "hunter": [3, 6],
    "warlock": [2, 4, 6],
    "demon_hunter": [2],
    "nature": [2, 4],
    "mech": [2, 4],
    "shaman": [2],
};

SPICIES = [
    "undead",
    "human",
    "goblin",
    "savage",
    "primordial",
    "dragon",
    "scaled",
    "troll",
    "brawny",
    "bloodbound",
    "elf",
    "deadeye",
    "demon"
].reverse(); //this reverse is workaround
JOBS = [
    "assassin",
    "hunter",
    "knight",
    "warrior",
    "nature",
    "mage",
    "warlock",
    "mech",
    "shaman",
    "demon_hunter"
].reverse();
ALLIANCES = SPICIES.concat(JOBS);
W = (SPICIES.length + 1) * CELL_STEP - CELL_SPACING + 2 * CELL_PADDING;
H = (JOBS.length + 1) * CELL_STEP - CELL_SPACING + 2 * CELL_PADDING;
